service: crud-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:139181118930:table/taskTable

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  create:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post
  get:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: get
  getAll:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  update:
    handler: src/updateTask.updateTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: put
  delete:
    handler: src/deleteTask.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete
resources:
  Resources:
    tasksTables:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: taskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
# plugins:
#   - serverless-offline
